./ppi_level_3.py -m model2 -r ppi_m1_con --sign pos
./ppi_level_3.py -m model2 -r ppi_m2_con --sign pos
./ppi_level_3.py -m model2 -r ppi_m3_con --sign pos
./ppi_level_3.py -m model2 -r ppi_m4_con --sign pos
./ppi_level_3.py -m model3 -r ppi_m1_con --sign pos
./ppi_level_3.py -m model3 -r ppi_m2_con --sign pos
./ppi_level_3.py -m model3 -r ppi_m3_con --sign pos
./ppi_level_3.py -m model3 -r ppi_m4_con --sign pos
./ppi_level_3.py -m model3_g -r ppi_m1_con --sign pos
./ppi_level_3.py -m model3_g -r ppi_m2_con --sign pos
./ppi_level_3.py -m model3_g -r ppi_m3_con --sign pos
./ppi_level_3.py -m model3_g -r ppi_m4_con --sign pos
./ppi_level_3.py -m model1 -r ppi_m1_con --sign neg
./ppi_level_3.py -m model2 -r ppi_m1_con --sign neg
./ppi_level_3.py -m model2 -r ppi_m2_con --sign neg
./ppi_level_3.py -m model2 -r ppi_m3_con --sign neg
./ppi_level_3.py -m model2 -r ppi_m4_con --sign neg
./ppi_level_3.py -m model3 -r ppi_m1_con --sign neg
./ppi_level_3.py -m model3 -r ppi_m2_con --sign neg
./ppi_level_3.py -m model3 -r ppi_m3_con --sign neg
./ppi_level_3.py -m model3 -r ppi_m4_con --sign neg
./ppi_level_3.py -m model3_g -r ppi_m1_con --sign neg
./ppi_level_3.py -m model3_g -r ppi_m2_con --sign neg
./ppi_level_3.py -m model3_g -r ppi_m3_con --sign neg
./ppi_level_3.py -m model3_g -r ppi_m4_con --sign neg
