feat $DATA_LOC/derivatives/level_3/model2/m1.fsf
feat $DATA_LOC/derivatives/level_3/model2/m2.fsf
feat $DATA_LOC/derivatives/level_3/model2/m3.fsf
feat $DATA_LOC/derivatives/level_3/model2/m4.fsf
feat $DATA_LOC/derivatives/level_3/model2/m1_rt.fsf
feat $DATA_LOC/derivatives/level_3/model2/m2_rt.fsf
feat $DATA_LOC/derivatives/level_3/model2/m3_rt.fsf
feat $DATA_LOC/derivatives/level_3/model2/m4_rt.fsf
feat $DATA_LOC/derivatives/level_3/model2/pe_lv.fsf
feat $DATA_LOC/derivatives/level_3/model2/pe_hv.fsf
feat $DATA_LOC/derivatives/level_3/model2/junk.fsf
