randomise -i $MODEL_DIR/m1/all_l2_model3_m1.nii.gz -o $MODEL_DIR/m1/rand_anova/group_diff -d $MODEL_DIR/m1/model3_m1.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/m2/all_l2_model3_m2.nii.gz -o $MODEL_DIR/m2/rand_anova/group_diff -d $MODEL_DIR/m2/model3_m2.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/m3/all_l2_model3_m3.nii.gz -o $MODEL_DIR/m3/rand_anova/group_diff -d $MODEL_DIR/m3/model3_m3.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/m4/all_l2_model3_m4.nii.gz -o $MODEL_DIR/m4/rand_anova/group_diff -d $MODEL_DIR/m4/model3_m4.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/m1_rt/all_l2_model3_m1_rt.nii.gz -o $MODEL_DIR/m1_rt/rand_anova/group_diff -d $MODEL_DIR/m1_rt/model3_m1_rt.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/m2_rt/all_l2_model3_m2_rt.nii.gz -o $MODEL_DIR/m2_rt/rand_anova/group_diff -d $MODEL_DIR/m2_rt/model3_m2_rt.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/m3_rt/all_l2_model3_m3_rt.nii.gz -o $MODEL_DIR/m3_rt/rand_anova/group_diff -d $MODEL_DIR/m3_rt/model3_m3_rt.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/m4_rt/all_l2_model3_m4_rt.nii.gz -o $MODEL_DIR/m4_rt/rand_anova/group_diff -d $MODEL_DIR/m4_rt/model3_m4_rt.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/hpe/all_l2_model3_hpe.nii.gz -o $MODEL_DIR/hpe/rand_anova/group_diff -d $MODEL_DIR/hpe/model3_hpe.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/lpe/all_l2_model3_lpe.nii.gz -o $MODEL_DIR/lpe/rand_anova/group_diff -d $MODEL_DIR/lpe/model3_lpe.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/junk/all_l2_model3_junk.nii.gz -o $MODEL_DIR/junk/rand_anova/group_diff -d $MODEL_DIR/junk/model3_junk.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/task_on/all_l2_model3_task_on.nii.gz -o $MODEL_DIR/task_on/rand_anova/group_diff -d $MODEL_DIR/task_on/model3_task_on.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
randomise -i $MODEL_DIR/rt/all_l2_model3_rt.nii.gz -o $MODEL_DIR/rt/rand_anova/group_diff -d $MODEL_DIR/rt/model3_rt.mat -t $MODEL_DIR/design.con -f $MODEL_DIR/design.fts -n 1000 -T
