python fsl_randomise.py --mnum model1 --reg m1 -tf
python fsl_randomise.py --mnum model1 --reg m2 -tf
python fsl_randomise.py --mnum model1 --reg m3 -tf
python fsl_randomise.py --mnum model1 --reg m4 -tf
python fsl_randomise.py --mnum model1 --reg hpe -tf
python fsl_randomise.py --mnum model1 --reg lpe -tf
python fsl_randomise.py --mnum model1 --reg pe -tf
python fsl_randomise.py --mnum model1 --reg task_on -tf
python fsl_randomise.py --mnum model1 --reg var_sen -tf
python fsl_randomise.py --mnum model1 --reg ev_sen -tf
python fsl_randomise.py --mnum model2 --reg m1 -tf
python fsl_randomise.py --mnum model1 --reg m2 -tf
python fsl_randomise.py --mnum model2 --reg m3 -tf
python fsl_randomise.py --mnum model2 --reg m4 -tf
python fsl_randomise.py --mnum model2 --reg hpe -tf
python fsl_randomise.py --mnum model2 --reg lpe -tf
python fsl_randomise.py --mnum model2 --reg pe -tf
python fsl_randomise.py --mnum model2 --reg task_on -tf
python fsl_randomise.py --mnum model2 --reg var_sen -tf
python fsl_randomise.py --mnum model2 --reg ev_sen -tf
python fsl_randomise.py --mnum model3 --reg m1 -tf
python fsl_randomise.py --mnum model3 --reg m2 -tf
python fsl_randomise.py --mnum model3 --reg m3 -tf
python fsl_randomise.py --mnum model3 --reg m4 -tf
python fsl_randomise.py --mnum model3 --reg hpe -tf
python fsl_randomise.py --mnum model3 --reg lpe -tf
python fsl_randomise.py --mnum model3 --reg pe -tf
python fsl_randomise.py --mnum model3 --reg task_on -tf
python fsl_randomise.py --mnum model3 --reg var_sen -tf
python fsl_randomise.py --mnum model3 --reg ev_sen -tf
