python fsl_randomise.py --mnum model2 --reg m1
python fsl_randomise.py --mnum model2 --reg m2
python fsl_randomise.py --mnum model2 --reg m3
python fsl_randomise.py --mnum model2 --reg m4
python fsl_randomise.py --mnum model2 --reg hpe
python fsl_randomise.py --mnum model2 --reg lpe
python fsl_randomise.py --mnum model2 --reg pe
python fsl_randomise.py --mnum model2 --reg task_on
python fsl_randomise.py --mnum model2 --reg var_sen
python fsl_randomise.py --mnum model2 --reg ev_sen
python fsl_randomise.py --mnum model3 --reg m1
python fsl_randomise.py --mnum model3 --reg m2
python fsl_randomise.py --mnum model3 --reg m3
python fsl_randomise.py --mnum model3 --reg m4
python fsl_randomise.py --mnum model3 --reg hpe
python fsl_randomise.py --mnum model3 --reg lpe
python fsl_randomise.py --mnum model3 --reg pe
python fsl_randomise.py --mnum model3 --reg task_on
python fsl_randomise.py --mnum model3 --reg var_sen
python fsl_randomise.py --mnum model3 --reg ev_sen
