python pred_rl.py --model_name Fit_alpha-beta-exp_Fix_lossave
python pred_rl.py --model_name Fit_alpha_neg-alpha_pos-beta-exp_Fix_lossave
python pred_rl.py --model_name Fit_alpha-beta-exp-lossave_Fix
python pred_rl.py --model_name Fit_alpha_neg-alpha_pos-beta-exp-lossave_Fix
python pred_rl.py --model_name Fit_alpha-beta-exp_neg-exp_pos_Fix_lossave
python pred_rl.py --model_name Fit_alpha_neg-alpha_pos-beta-exp_neg-exp_pos_Fix_lossave
python pred_rl.py --model_name Fit_alpha-beta-exp_neg-exp_pos-lossave_Fix
python pred_rl.py --model_name Fit_alpha_neg-alpha_pos-beta-exp_neg-exp_pos-lossave_Fix
python pred_rl.py --model_name Fit_alpha-beta_Fix_exp-lossave
python pred_rl.py --model_name Fit_alpha_neg-alpha_pos-beta_Fix_exp-lossave
python pred_rl.py --model_name Fit_alpha-beta-lossave_Fix_exp
python pred_rl.py --model_name Fit_alpha_neg-alpha_pos-beta-lossave_Fix_exp
