./get_all_roi_vals.py -l l_vstr -r hpe -v beta
./get_all_roi_vals.py -l r_vstr -r hpe -v beta
./get_all_roi_vals.py -l acc -r hpe -v beta
./get_all_roi_vals.py -l l_ains -r hpe -v beta
./get_all_roi_vals.py -l pcc -r hpe -v beta
./get_all_roi_vals.py -l pre_sma -r hpe -v beta
./get_all_roi_vals.py -l r_ains -r hpe -v beta
./get_all_roi_vals.py -l vmpfc -r hpe -v beta
./get_all_roi_vals.py -l l_vstr -r lpe -v beta
./get_all_roi_vals.py -l r_vstr -r lpe -v beta
./get_all_roi_vals.py -l acc -r lpe -v beta
./get_all_roi_vals.py -l l_ains -r lpe -v beta
./get_all_roi_vals.py -l pcc -r lpe -v beta
./get_all_roi_vals.py -l pre_sma -r lpe -v beta
./get_all_roi_vals.py -l r_ains -r lpe -v beta
./get_all_roi_vals.py -l vmpfc -r lpe -v beta
