python level_3.py -m model2 -r m1 --runstats
python level_3.py -m model2 -r m2 --runstats
python level_3.py -m model2 -r m3 --runstats
python level_3.py -m model2 -r m4 --runstats
python level_3.py -m model2 -r m1_rt --runstats
python level_3.py -m model2 -r m2_rt --runstats
python level_3.py -m model2 -r m3_rt --runstats
python level_3.py -m model2 -r m4_rt --runstats
python level_3.py -m model2 -r gain --runstats
python level_3.py -m model2 -r loss --runstats
python level_3.py -m model2 -r junk --runstats
python level_3.py -m model2 -r task_on --runstats
python level_3.py -m model2 -r rt --runstats
python level_3.py -m model2 -r gain-loss --runstats
python level_3.py -m model2 -r loss-gain --runstats
