python level_3.py -m model1 -r m1 --runstats
python level_3.py -m model1 -r m2 --runstats
python level_3.py -m model1 -r m3 --runstats
python level_3.py -m model1 -r m4 --runstats
python level_3.py -m model1 -r m1_rt --runstats
python level_3.py -m model1 -r m2_rt --runstats
python level_3.py -m model1 -r m3_rt --runstats
python level_3.py -m model1 -r m4_rt --runstats
python level_3.py -m model1 -r pe --runstats
python level_3.py -m model1 -r junk --runstats
python level_3.py -m model1 -r task_on --runstats
python level_3.py -m model1 -r rt --runstats
