./level_3.py -m model2 -r m1_ev --sign pos -ev True
./level_3.py -m model2 -r m2_ev --sign pos -ev True
./level_3.py -m model2 -r m3_ev --sign pos -ev True
./level_3.py -m model2 -r m4_ev --sign pos -ev True
./level_3.py -m model2 -r hpe --sign pos -ev True
./level_3.py -m model2 -r lpe --sign pos -ev True
./level_3.py -m model2 -r pe --sign pos -ev True
./level_3.py -m model2 -r task_on --sign pos -ev True
./level_3.py -m model2 -r rt --sign pos -ev True
./level_3.py -m model2 -r var_sen --sign pos -ev True
./level_3.py -m model2 -r ev_sen --sign pos -ev True
./level_3.py -m model3 -r m1_ev --sign pos -ev True
./level_3.py -m model3 -r m2_ev --sign pos -ev True
./level_3.py -m model3 -r m3_ev --sign pos -ev True
./level_3.py -m model3 -r m4_ev --sign pos -ev True
./level_3.py -m model3 -r hpe --sign pos -ev True
./level_3.py -m model3 -r lpe --sign pos -ev True
./level_3.py -m model3 -r pe --sign pos -ev True
./level_3.py -m model3 -r task_on --sign pos -ev True
./level_3.py -m model3 -r rt --sign pos -ev True
./level_3.py -m model3 -r var_sen --sign pos -ev True
./level_3.py -m model3 -r ev_sen --sign pos -ev True
./level_3.py -m model3_g -r m1_ev --sign pos -ev True
./level_3.py -m model3_g -r m2_ev --sign pos -ev True
./level_3.py -m model3_g -r m3_ev --sign pos -ev True
./level_3.py -m model3_g -r m4_ev --sign pos -ev True
./level_3.py -m model3_g -r hpe --sign pos -ev True
./level_3.py -m model3_g -r lpe --sign pos -ev True
./level_3.py -m model3_g -r pe --sign pos -ev True
./level_3.py -m model3_g -r task_on --sign pos -ev True
./level_3.py -m model3_g -r rt --sign pos -ev True
./level_3.py -m model3_g -r var_sen --sign pos -ev True
./level_3.py -m model3_g -r ev_sen --sign pos -ev True
./level_3.py -m model2 -r m1_ev --sign neg -ev True
./level_3.py -m model2 -r m2_ev --sign neg -ev True
./level_3.py -m model2 -r m3_ev --sign neg -ev True
./level_3.py -m model2 -r m4_ev --sign neg -ev True
./level_3.py -m model2 -r hpe --sign neg -ev True
./level_3.py -m model2 -r lpe --sign neg -ev True
./level_3.py -m model2 -r pe --sign neg -ev True
./level_3.py -m model2 -r task_on --sign neg -ev True
./level_3.py -m model2 -r rt --sign neg -ev True
./level_3.py -m model2 -r var_sen --sign neg -ev True
./level_3.py -m model2 -r ev_sen --sign neg -ev True
./level_3.py -m model3 -r m1_ev --sign neg -ev True
./level_3.py -m model3 -r m2_ev --sign neg -ev True
./level_3.py -m model3 -r m3_ev --sign neg -ev True
./level_3.py -m model3 -r m4_ev --sign neg -ev True
./level_3.py -m model3 -r hpe --sign neg -ev True
./level_3.py -m model3 -r lpe --sign neg -ev True
./level_3.py -m model3 -r pe --sign neg -ev True
./level_3.py -m model3 -r task_on --sign neg -ev True
./level_3.py -m model3 -r rt --sign neg -ev True
./level_3.py -m model3 -r var_sen --sign neg -ev True
./level_3.py -m model3 -r ev_sen --sign neg -ev True
./level_3.py -m model3_g -r m1_ev --sign neg -ev True
./level_3.py -m model3_g -r m2_ev --sign neg -ev True
./level_3.py -m model3_g -r m3_ev --sign neg -ev True
./level_3.py -m model3_g -r m4_ev --sign neg -ev True
./level_3.py -m model3_g -r hpe --sign neg -ev True
./level_3.py -m model3_g -r lpe --sign neg -ev True
./level_3.py -m model3_g -r pe --sign neg -ev True
./level_3.py -m model3_g -r task_on --sign neg -ev True
./level_3.py -m model3_g -r rt --sign neg -ev True
./level_3.py -m model3_g -r var_sen --sign neg -ev True
./level_3.py -m model3_g -r ev_sen --sign neg -ev True
