python level_3.py -m model3 -r m1 --runstats
python level_3.py -m model3 -r m2 --runstats
python level_3.py -m model3 -r m3 --runstats
python level_3.py -m model3 -r m4 --runstats
python level_3.py -m model3 -r hpe --runstats
python level_3.py -m model3 -r lpe --runstats
python level_3.py -m model3 -r pe --runstats
python level_3.py -m model3 -r task_on --runstats
python level_3.py -m model3 -r rt --runstats
python level_3.py -m model3 -r var_sen --runstats
python level_3.py -m model3 -r ev_sen --runstats
