./level_3.py -m model1 -r m1_ev --sign pos -ev True
./level_3.py -m model1 -r m2_ev --sign pos -ev True
./level_3.py -m model1 -r m3_ev --sign pos -ev True
./level_3.py -m model1 -r m4_ev --sign pos -ev True
./level_3.py -m model1 -r hpe --sign pos -ev True
./level_3.py -m model1 -r lpe --sign pos -ev True
./level_3.py -m model1 -r pe --sign pos -ev True
./level_3.py -m model1 -r task_on --sign pos -ev True
./level_3.py -m model1 -r rt --sign pos -ev True
./level_3.py -m model1 -r var_sen --sign pos -ev True
./level_3.py -m model1 -r ev_sen --sign pos -ev True
./level_3.py -m model2 -r m1_ev --sign pos -ev True
./level_3.py -m model2 -r m2_ev --sign pos -ev True
./level_3.py -m model2 -r m3_ev --sign pos -ev True
./level_3.py -m model2 -r m4_ev --sign pos -ev True
./level_3.py -m model2 -r hpe --sign pos -ev True
./level_3.py -m model2 -r lpe --sign pos -ev True
./level_3.py -m model2 -r pe --sign pos -ev True
./level_3.py -m model2 -r task_on --sign pos -ev True
./level_3.py -m model2 -r rt --sign pos -ev True
./level_3.py -m model2 -r var_sen --sign pos -ev True
./level_3.py -m model2 -r ev_sen --sign pos -ev True
./level_3.py -m model3 -r m1_ev --sign pos -ev True
./level_3.py -m model3 -r m2_ev --sign pos -ev True
./level_3.py -m model3 -r m3_ev --sign pos -ev True
./level_3.py -m model3 -r m4_ev --sign pos -ev True
./level_3.py -m model3 -r hpe --sign pos -ev True
./level_3.py -m model3 -r lpe --sign pos -ev True
./level_3.py -m model3 -r pe --sign pos -ev True
./level_3.py -m model3 -r task_on --sign pos -ev True
./level_3.py -m model3 -r rt --sign pos -ev True
./level_3.py -m model3 -r var_sen --sign pos -ev True
./level_3.py -m model3 -r ev_sen --sign pos -ev True
./level_3.py -m model3_g -r m1_ev --sign pos -ev True
./level_3.py -m model3_g -r m2_ev --sign pos -ev True
./level_3.py -m model3_g -r m3_ev --sign pos -ev True
./level_3.py -m model3_g -r m4_ev --sign pos -ev True
./level_3.py -m model3_g -r hpe --sign pos -ev True
./level_3.py -m model3_g -r lpe --sign pos -ev True
./level_3.py -m model3_g -r pe --sign pos -ev True
./level_3.py -m model3_g -r task_on --sign pos -ev True
./level_3.py -m model3_g -r rt --sign pos -ev True
./level_3.py -m model3_g -r var_sen --sign pos -ev True
./level_3.py -m model3_g -r ev_sen --sign pos -ev True
./level_3.py -m model4 -r m1_ev --sign pos -ev True
./level_3.py -m model4 -r m2_ev --sign pos -ev True
./level_3.py -m model4 -r m3_ev --sign pos -ev True
./level_3.py -m model4 -r m4_ev --sign pos -ev True
./level_3.py -m model4 -r hpe --sign pos -ev True
./level_3.py -m model4 -r lpe --sign pos -ev True
./level_3.py -m model4 -r pe --sign pos -ev True
./level_3.py -m model4 -r task_on --sign pos -ev True
./level_3.py -m model4 -r rt --sign pos -ev True
./level_3.py -m model4 -r var_sen --sign pos -ev True
./level_3.py -m model4 -r ev_sen --sign pos -ev True
./level_3.py -m model4_h -r m1_ev --sign pos -ev True
./level_3.py -m model4_h -r m2_ev --sign pos -ev True
./level_3.py -m model4_h -r m3_ev --sign pos -ev True
./level_3.py -m model4_h -r m4_ev --sign pos -ev True
./level_3.py -m model4_h -r hpe --sign pos -ev True
./level_3.py -m model4_h -r lpe --sign pos -ev True
./level_3.py -m model4_h -r pe --sign pos -ev True
./level_3.py -m model4_h -r task_on --sign pos -ev True
./level_3.py -m model4_h -r rt --sign pos -ev True
./level_3.py -m model4_h -r var_sen --sign pos -ev True
./level_3.py -m model4_h -r ev_sen --sign pos -ev True
./level_3.py -m model1 -r m1_ev --sign neg -ev True
./level_3.py -m model1 -r m2_ev --sign neg -ev True
./level_3.py -m model1 -r m3_ev --sign neg -ev True
./level_3.py -m model1 -r m4_ev --sign neg -ev True
./level_3.py -m model1 -r hpe --sign neg -ev True
./level_3.py -m model1 -r lpe --sign neg -ev True
./level_3.py -m model1 -r pe --sign neg -ev True
./level_3.py -m model1 -r task_on --sign neg -ev True
./level_3.py -m model1 -r rt --sign neg -ev True
./level_3.py -m model1 -r var_sen --sign neg -ev True
./level_3.py -m model1 -r ev_sen --sign neg -ev True
./level_3.py -m model2 -r m1_ev --sign neg -ev True
./level_3.py -m model2 -r m2_ev --sign neg -ev True
./level_3.py -m model2 -r m3_ev --sign neg -ev True
./level_3.py -m model2 -r m4_ev --sign neg -ev True
./level_3.py -m model2 -r hpe --sign neg -ev True
./level_3.py -m model2 -r lpe --sign neg -ev True
./level_3.py -m model2 -r pe --sign neg -ev True
./level_3.py -m model2 -r task_on --sign neg -ev True
./level_3.py -m model2 -r rt --sign neg -ev True
./level_3.py -m model2 -r var_sen --sign neg -ev True
./level_3.py -m model2 -r ev_sen --sign neg -ev True
./level_3.py -m model3 -r m1_ev --sign neg -ev True
./level_3.py -m model3 -r m2_ev --sign neg -ev True
./level_3.py -m model3 -r m3_ev --sign neg -ev True
./level_3.py -m model3 -r m4_ev --sign neg -ev True
./level_3.py -m model3 -r hpe --sign neg -ev True
./level_3.py -m model3 -r lpe --sign neg -ev True
./level_3.py -m model3 -r pe --sign neg -ev True
./level_3.py -m model3 -r task_on --sign neg -ev True
./level_3.py -m model3 -r rt --sign neg -ev True
./level_3.py -m model3 -r var_sen --sign neg -ev True
./level_3.py -m model3 -r ev_sen --sign neg -ev True
./level_3.py -m model3_g -r m1_ev --sign neg -ev True
./level_3.py -m model3_g -r m2_ev --sign neg -ev True
./level_3.py -m model3_g -r m3_ev --sign neg -ev True
./level_3.py -m model3_g -r m4_ev --sign neg -ev True
./level_3.py -m model3_g -r hpe --sign neg -ev True
./level_3.py -m model3_g -r lpe --sign neg -ev True
./level_3.py -m model3_g -r pe --sign neg -ev True
./level_3.py -m model3_g -r task_on --sign neg -ev True
./level_3.py -m model3_g -r rt --sign neg -ev True
./level_3.py -m model3_g -r var_sen --sign neg -ev True
./level_3.py -m model3_g -r ev_sen --sign neg -ev True
./level_3.py -m model4 -r m1_ev --sign neg -ev True
./level_3.py -m model4 -r m2_ev --sign neg -ev True
./level_3.py -m model4 -r m3_ev --sign neg -ev True
./level_3.py -m model4 -r m4_ev --sign neg -ev True
./level_3.py -m model4 -r hpe --sign neg -ev True
./level_3.py -m model4 -r lpe --sign neg -ev True
./level_3.py -m model4 -r pe --sign neg -ev True
./level_3.py -m model4 -r task_on --sign neg -ev True
./level_3.py -m model4 -r rt --sign neg -ev True
./level_3.py -m model4 -r var_sen --sign neg -ev True
./level_3.py -m model4 -r ev_sen --sign neg -ev True
./level_3.py -m model4_h -r m1_ev --sign neg -ev True
./level_3.py -m model4_h -r m2_ev --sign neg -ev True
./level_3.py -m model4_h -r m3_ev --sign neg -ev True
./level_3.py -m model4_h -r m4_ev --sign neg -ev True
./level_3.py -m model4_h -r hpe --sign neg -ev True
./level_3.py -m model4_h -r lpe --sign neg -ev True
./level_3.py -m model4_h -r pe --sign neg -ev True
./level_3.py -m model4_h -r task_on --sign neg -ev True
./level_3.py -m model4_h -r rt --sign neg -ev True
./level_3.py -m model4_h -r var_sen --sign neg -ev True
./level_3.py -m model4_h -r ev_sen --sign neg -ev True
./level_3.py -m model4_c -r m1_ev --sign pos -ev True
./level_3.py -m model4_c -r m2_ev --sign pos -ev True
./level_3.py -m model4_c -r m3_ev --sign pos -ev True
./level_3.py -m model4_c -r m4_ev --sign pos -ev True
./level_3.py -m model4_c -r hpe --sign pos -ev True
./level_3.py -m model4_c -r lpe --sign pos -ev True
./level_3.py -m model4_c -r pe --sign pos -ev True
./level_3.py -m model4_c -r task_on --sign pos -ev True
./level_3.py -m model4_c -r rt --sign pos -ev True
./level_3.py -m model4_c -r var_sen --sign pos -ev True
./level_3.py -m model4_c -r ev_sen --sign pos -ev True
./level_3.py -m model4_c -r m1_ev --sign neg -ev True
./level_3.py -m model4_c -r m2_ev --sign neg -ev True
./level_3.py -m model4_c -r m3_ev --sign neg -ev True
./level_3.py -m model4_c -r m4_ev --sign neg -ev True
./level_3.py -m model4_c -r hpe --sign neg -ev True
./level_3.py -m model4_c -r lpe --sign neg -ev True
./level_3.py -m model4_c -r pe --sign neg -ev True
./level_3.py -m model4_c -r task_on --sign neg -ev True
./level_3.py -m model4_c -r rt --sign neg -ev True
./level_3.py -m model4_c -r var_sen --sign neg -ev True
./level_3.py -m model4_c -r ev_sen --sign neg -ev True
