./level_3.py -m model1 -r m1
./level_3.py -m model1 -r m2
./level_3.py -m model1 -r m3
./level_3.py -m model1 -r m4
./level_3.py -m model1 -r hpe
./level_3.py -m model1 -r lpe
./level_3.py -m model1 -r pe
./level_3.py -m model1 -r task_on
./level_3.py -m model1 -r rt
./level_3.py -m model1 -r var_sen
./level_3.py -m model1 -r ev_sen
./level_3.py -m model2 -r m1
./level_3.py -m model2 -r m2
./level_3.py -m model2 -r m3
./level_3.py -m model2 -r m4
./level_3.py -m model2 -r hpe
./level_3.py -m model2 -r lpe
./level_3.py -m model2 -r pe
./level_3.py -m model2 -r task_on
./level_3.py -m model2 -r rt
./level_3.py -m model2 -r var_sen
./level_3.py -m model2 -r ev_sen
./level_3.py -m model3 -r m1
./level_3.py -m model3 -r m2
./level_3.py -m model3 -r m3
./level_3.py -m model3 -r m4
./level_3.py -m model3 -r hpe
./level_3.py -m model3 -r lpe
./level_3.py -m model3 -r pe
./level_3.py -m model3 -r task_on
./level_3.py -m model3 -r rt
./level_3.py -m model3 -r var_sen
./level_3.py -m model3 -r ev_sen
./level_3.py -m model4 -r m1
./level_3.py -m model4 -r m2
./level_3.py -m model4 -r m3
./level_3.py -m model4 -r m4
./level_3.py -m model4 -r hpe
./level_3.py -m model4 -r lpe
./level_3.py -m model4 -r pe
./level_3.py -m model4 -r task_on
./level_3.py -m model4 -r rt
./level_3.py -m model4 -r var_sen
./level_3.py -m model4 -r ev_sen
