./level_3.py -m model3 -r m1 --runstats
./level_3.py -m model3 -r m2 --runstats
./level_3.py -m model3 -r m3 --runstats
./level_3.py -m model3 -r m4 --runstats
./level_3.py -m model3 -r hpe --runstats
./level_3.py -m model3 -r lpe --runstats
./level_3.py -m model3 -r pe --runstats
./level_3.py -m model3 -r task_on --runstats
./level_3.py -m model3 -r rt --runstats
./level_3.py -m model3 -r var_sen --runstats
./level_3.py -m model3 -r ev_sen --runstats
