./level_3.py -m model4_c -r m1 --sign pos
./level_3.py -m model4_c -r m2 --sign pos
./level_3.py -m model4_c -r m3 --sign pos
./level_3.py -m model4_c -r m4 --sign pos
./level_3.py -m model4_c -r hpe --sign pos
./level_3.py -m model4_c -r lpe --sign pos
./level_3.py -m model4_c -r pe --sign pos
./level_3.py -m model4_c -r task_on --sign pos
./level_3.py -m model4_c -r rt --sign pos
./level_3.py -m model4_c -r var_sen --sign pos
./level_3.py -m model4_c -r ev_sen --sign pos
./level_3.py -m model4_c -r m1 --sign neg
./level_3.py -m model4_c -r m2 --sign neg
./level_3.py -m model4_c -r m3 --sign neg
./level_3.py -m model4_c -r m4 --sign neg
./level_3.py -m model4_c -r hpe --sign neg
./level_3.py -m model4_c -r lpe --sign neg
./level_3.py -m model4_c -r pe --sign neg
./level_3.py -m model4_c -r task_on --sign neg
./level_3.py -m model4_c -r rt --sign neg
./level_3.py -m model4_c -r var_sen --sign neg
./level_3.py -m model4_c -r ev_sen --sign neg
