./level_3.py -m model2 -r m1 --sign pos
./level_3.py -m model2 -r m2 --sign pos
./level_3.py -m model2 -r m3 --sign pos
./level_3.py -m model2 -r m4 --sign pos
./level_3.py -m model2 -r hpe --sign pos
./level_3.py -m model2 -r lpe --sign pos
./level_3.py -m model2 -r pe --sign pos
./level_3.py -m model2 -r task_on --sign pos
./level_3.py -m model2 -r rt --sign pos
./level_3.py -m model2 -r var_sen --sign pos
./level_3.py -m model2 -r ev_sen --sign pos
./level_3.py -m model2 -r m1 --sign neg
./level_3.py -m model2 -r m2 --sign neg
./level_3.py -m model2 -r m3 --sign neg
./level_3.py -m model2 -r m4 --sign neg
./level_3.py -m model2 -r hpe --sign neg
./level_3.py -m model2 -r lpe --sign neg
./level_3.py -m model2 -r pe --sign neg
./level_3.py -m model2 -r task_on --sign neg
./level_3.py -m model2 -r rt --sign neg
./level_3.py -m model2 -r var_sen --sign neg
./level_3.py -m model2 -r ev_sen --sign neg
